// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { Address, BigInt, Bytes } from '@mimicprotocol/lib-ts'

declare namespace input {
  const chainId: i32
  var user: string | null
  var target: string | null
  var data: string | null
  var value: string | null
  var feeToken: string | null
  var feeAmount: string | null
}

// The class name is intentionally lowercase and plural to resemble a namespace when used in a task.
export class inputs {
  static get chainId(): i32 {
    return input.chainId
  }

  static get user(): Address {
    return Address.fromString(input.user!)
  }

  static get target(): Address {
    return Address.fromString(input.target!)
  }

  static get data(): Bytes {
    return Bytes.fromHexString(input.data!)
  }

  static get value(): BigInt {
    return BigInt.fromString(input.value!)
  }

  static get feeToken(): Address {
    return Address.fromString(input.feeToken!)
  }

  static get feeAmount(): BigInt {
    return BigInt.fromString(input.feeAmount!)
  }
}
