// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE MANUALLY.

declare namespace input {
  const chainId: i32
  const amount: i32
  const slippage: i32
}

// The class name is intentionally lowercase and plural to resemble a namespace when used in a task.
export class inputs {
  static get chainId(): i32 {
    return input.chainId
  }

  static get amount(): i32 {
    return input.amount
  }

  static get slippage(): i32 {
    return input.slippage
  }
}
