// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE MANUALLY.

declare namespace input {
  // The chain ID to use for the transaction
  const chainId: i32
}

// The class name is intentionally lowercase and plural to resemble a namespace when used in a task.
export class inputs {
  static get chainId(): i32 {
    return input.chainId
  }
}
